### ISSUE TITLE
Causing crash when thrown

### ISSUE THREAD

**Issue by biwhite** [Uthrom/SeeThisSnowball#1]
Error while running event SeeThisSnowball::on_entity_damaged (ID 97)
The mod See This Snowball? caused a non-recoverable error.
Please report this error to the mod author.

![2019-12-09-002330_grim](https://user-images.githubusercontent.com/3225320/70399294-9f29a580-1a1a-11ea-81ea-9e3138b42281.png)

**Comment by Uthrom** [comment]
Can you get me the relevant server log?

**Comment by Uthrom** [comment]
And/or link to a savefile I can use to reproduce the problem.

**Comment by Uthrom** [comment]
This is hopefully fixed in the latest release.
